<?php
// bill_payment_report_pdf.php
session_start();
require('config/dbcon.php');
require('fpdf/fpdf.php');
date_default_timezone_set('Asia/Manila');

// SECURITY: require logged-in user and allowed role
if (!isset($_SESSION['auth'])) {
    die("Unauthorized.");
}
$allowed_roles = ['admin', 'employee'];
$user_role = $_SESSION['auth_role'] ?? '';
if (!in_array($user_role, $allowed_roles)) {
    die("You are not authorized to access this page.");
}

// ---------------------------
// Business header details
// ---------------------------
$logo_path   = 'images/logo.png';           
$business    = 'Monings Rental Services';
$address     = '1438-B M.J.Cuenco Ave, Brgy Mabolo, Cebu City';
$phone       = '09123456789';
$email       = 'moning@gmail.com';

// ---------------------------
// Build filters (mirror report_bill.php)
// ---------------------------
$where = "";

// SEARCH
if (!empty($_GET['search'])) {
    $s = mysqli_real_escape_string($con, trim($_GET['search']));
    $where .= " AND (
        CONCAT(r.first_name, ' ', r.last_name) LIKE '%$s%' OR
        r.first_name LIKE '%$s%' OR
        r.last_name LIKE '%$s%' OR
        u.name LIKE '%$s%' OR
        b.reference_id LIKE '%$s%' OR
        b.billing_month LIKE '%$s%' OR
        b.status LIKE '%$s%' OR
        p.payment_type LIKE '%$s%' OR
        b.generated_by LIKE '%$s%' OR
        b.generated_role LIKE '%$s%'
    )";
    $applied_filters[] = "Search: \"$s\"";
}

// DATE RANGE
if (!empty($_GET['start_date']) && !empty($_GET['end_date'])) {
    $start = mysqli_real_escape_string($con, $_GET['start_date']);
    $end   = mysqli_real_escape_string($con, $_GET['end_date']);
    $where .= " AND DATE(b.created_at) BETWEEN '$start' AND '$end'";
    $applied_filters[] = "Date: $start to $end";
}

// MONTH
if (!empty($_GET['month'])) {
    $month = intval($_GET['month']);
    if ($month >=1 && $month <= 12) {
        $where .= " AND MONTH(b.created_at) = '$month'";
        $applied_filters[] = "Month: " . date("F", mktime(0,0,0,$month,1));
    }
}

// YEAR
if (!empty($_GET['year'])) {
    $year = intval($_GET['year']);
    if ($year >= 2000 && $year <= 2100) {
        $where .= " AND YEAR(b.created_at) = '$year'";
        $applied_filters[] = "Year: $year";
    }
}

// CREATOR
if (!empty($_GET['creator_name'])) {
    $creator_name = mysqli_real_escape_string($con, $_GET['creator_name']);
    $where .= " AND (
        b.generated_by LIKE '%$creator_name%' OR b.generated_role LIKE '%$creator_name%'
    )";
    $applied_filters[] = "Generated by: \"$creator_name\"";
}

// OPTIONAL: status filter (if you add this in UI later)
if (!empty($_GET['status'])) {
    $status_filter = mysqli_real_escape_string($con, $_GET['status']);
    $where .= " AND b.status = '$status_filter'";
    $applied_filters[] = "Status: " . htmlspecialchars($status_filter);
}

// ---------------------------
// Main query: get ALL rows matching filters (no limit)
// ---------------------------
$sql = "
    SELECT
        b.id AS bill_id,
        b.reference_id,
        b.billing_month,
        b.due_date,
        b.unit_price,
        b.addon_total,
        b.total_amount,
        b.late_fee,
        b.status AS bill_status,
        b.created_at,
        b.generated_by,
        b.generated_role,
        CONCAT(r.first_name, ' ', r.last_name) AS renter_name,
        u.name AS unit_name,
        IFNULL(SUM(p.amount), 0) AS total_paid,
        GROUP_CONCAT(DISTINCT p.payment_type SEPARATOR ', ') AS payment_types
    FROM bills b
    LEFT JOIN payments p ON b.id = p.bill_id
    LEFT JOIN renters r ON b.renter_id = r.id
    LEFT JOIN units u ON b.unit_id = u.id
    WHERE 1=1
    $where
    GROUP BY b.id
    ORDER BY b.created_at DESC
";

$result = mysqli_query($con, $sql);
if (!$result) {
    die("Query failed: " . mysqli_error($con));
}

// Pre-calc totals for the summary footer
$total_bills = 0;
$sum_total_amount = 0.00;
$sum_total_paid = 0.00;
$rows = [];
while ($row = mysqli_fetch_assoc($result)) {
    $rows[] = $row;
    $total_bills++;
    $sum_total_amount += floatval($row['total_amount']);
    $sum_total_paid += floatval($row['total_paid']);
}
$sum_remaining = $sum_total_amount - $sum_total_paid;
if ($sum_remaining < 0) $sum_remaining = 0; // remaining can't be negative for summary (overpaid shown separately)

// ---------------------------
// FPDF Class with header/footer
// ---------------------------
class ReportPDF extends FPDF {
    public $logo; public $business; public $address; public $phone; public $email;
    function Header() {
        // empty: we use custom headerSection in main script to control spacing
    }
    function headerSection() {
        // this function will be called by the script (so we can pass dynamic values)
    }
    // footer with page numbers
    function Footer() {
        $this->SetY(-12);
        $this->SetFont('Arial','I',8);
        $this->Cell(0,6,'Page '.$this->PageNo().' of {nb}',0,0,'C');
    }

    // Compute number of lines a MultiCell will take
function NbLines($w, $txt)
{
    $cw = &$this->CurrentFont['cw'];
    if($w==0) $w=$this->w-$this->rMargin-$this->x;
    $wmax=($w-2*$this->cMargin)*1000/$this->FontSize;
    $s=str_replace("\r",'',$txt);
    $nb=strlen($s);
    if($nb>0 && $s[$nb-1]=="\n") $nb--;
    $sep=-1;
    $i=0;
    $j=0;
    $l=0;
    $nl=1;
    while($i<$nb)
    {
        $c=$s[$i];
        if($c=="\n")
        {
            $i++;
            $sep=-1;
            $j=$i;
            $l=0;
            $nl++;
            continue;
        }
        if($c==' ') $sep=$i;
        $l+=$cw[$c];
        if($l>$wmax)
        {
            if($sep==-1)
            {
                if($i==$j) $i++;
            }
            else $i=$sep+1;
            $sep=-1;
            $j=$i;
            $l=0;
            $nl++;
        }
        else $i++;
    }
    return $nl;
}

}

// ---------------------------
// Generate PDF
// ---------------------------
$pdf = new ReportPDF('L','mm','A4');
$pdf->AliasNbPages();
$pdf->SetAutoPageBreak(true, 18);
$pdf->AddPage();
$pdf->SetMargins(8,8,8);

// HEADER (logo + business lines) - mimics your receipt header
if (file_exists($logo_path)) {
    $pdf->Image($logo_path, 10, 8, 28); // x, y, width
    // leave space for logo
    $pdf->SetXY(40, 10);
} else {
    $pdf->SetXY(10, 10);
}
$pdf->SetFont('Arial','B',14);
$pdf->Cell(0,6, $business, 0, 1, 'C');
$pdf->SetFont('Arial','',10);
$pdf->Cell(0,5, $address, 0, 1, 'C');
$pdf->Cell(0,5, "Phone: $phone | Email: $email", 0, 1, 'C');
$pdf->Ln(3);

// Title & filter summary
$pdf->SetFont('Arial','B',12);
$pdf->Cell(0,7,'Bills & Payments Report', 0, 1, 'C');
$pdf->Ln(2);

$pdf->SetFont('Arial','',9);
if (!empty($applied_filters)) {
    $pdf->MultiCell(0,5, 'Filters: ' . implode(' | ', $applied_filters));
    $pdf->Ln(2);
}

// Table header
$pdf->SetFont('Arial','B',9);
$pdf->SetFillColor(60,60,60);
$pdf->SetTextColor(255,255,255);

$headers = [
    '#','Reference','Renter','Unit','Billing Month','Due Date',
    'Total Amt','Paid','Payment Type(s)','Status','Role','Created At'
];

$widths = [
    5,   // #
    24,  // Reference
    28,  // Renter
    22,  // Unit
    22,  // Billing Month
    22,  // Due Date
    20,  // Total Amount
    20,  // Paid
    25,  // Payment Types
    16,  // Status
    14,  // Role
    28   // Created At
];


for ($i=0; $i<count($headers); $i++) {
    $pdf->Cell($widths[$i],8, $headers[$i], 1, 0, 'C', true);
}
$pdf->Ln();

// Table body
$pdf->SetFont('Arial','',9);
$pdf->SetTextColor(0,0,0);

if (count($rows) === 0) {
    $pdf->Cell(array_sum($widths), 10, "No records found.", 1, 1, 'C');
} else {
    $counter = 1;
    foreach ($rows as $r) {
        // Basic values
        $ref = $r['reference_id'] ?? '—';
        $renter = $r['renter_name'] ?? '—';
        $unit = $r['unit_name'] ?? '—';
        // For Billing Month column, prefer b.billing_month if exists, otherwise use due_date month
        $billingMonth = $r['billing_month'] ? $r['billing_month'] : (!empty($r['due_date']) ? date('F Y', strtotime($r['due_date'])) : '—');
        $due = $r['due_date'] ? date('Y-m-d', strtotime($r['due_date'])) : '—';
        $total_amt = number_format(floatval($r['total_amount']), 2);
        $paid = number_format(floatval($r['total_paid']), 2);
        $ptype = $r['payment_types'] ?? '—';
        $status = ucfirst($r['bill_status'] ?? '—');
        $role = ucfirst($r['generated_role'] ?? '—');
        $created = !empty($r['created_at']) ? date('Y-m-d H:i', strtotime($r['created_at'])) : '—';

        // Row printing. Use MultiCell for payment types if it's long — implement manual cell wrapping.
        $x = $pdf->GetX();
        $y = $pdf->GetY();

        $pdf->Cell($widths[0],7,$counter,1);
        $pdf->Cell($widths[1],7,$ref,1);
        $pdf->Cell($widths[2],7,$renter,1);
        $pdf->Cell($widths[3],7,$unit,1);
        $pdf->Cell($widths[4],7,$billingMonth,1);
        $pdf->Cell($widths[5],7,$due,1);
        $pdf->Cell($widths[6],7,$total_amt,1,0,'R');
        $pdf->Cell($widths[7],7,$paid,1,0,'R');

        // Payment types cell: allow MultiCell
        // Save x,y; create a cell for ptype with given width and compute height using MultiCell
        $px = $pdf->GetX();
        $py = $pdf->GetY();

        // MultiCell for Payment Type
        $pdf->Cell($widths[8], 7, $ptype, 1, 0, 'L');

        // Calculate new height after MultiCell
        $newY = $pdf->GetY();
        $cellHeight = $newY - $py;

        // Move cursor to the right of payment type cell
        $pdf->SetXY($px + $widths[8], $py);

        // Add the rest of the cells with same height
        $pdf->Cell($widths[9], $cellHeight, $status, 1, 0, 'C');
        $pdf->Cell($widths[10], $cellHeight, $role, 1, 0, 'C');
        $pdf->Cell($widths[11], $cellHeight, $created, 1, 0, 'L');

        $pdf->Ln($cellHeight);


        $pdf->Cell($widths[9],7,$status,1,0,'C');
        $pdf->Cell($widths[10],7,$role,1);
        $pdf->Cell($widths[11],7,$created,1);

        $pdf->Ln();
        $counter++;
    }
}

// ---------------------------
// Summary Totals (centered box)
// ---------------------------
$pdf->Ln(4);
$pdf->SetFont('Arial','B',10);
$pdf->Cell(0,6,'Summary Totals',0,1,'C');
$pdf->SetFont('Arial','',9);

// We'll print totals aligned left and right
$leftColWidth = 120;
$rightColWidth = 60;

$pdf->Cell(40,6,'Total Bills:',0,0);
$pdf->Cell(30,6,$total_bills,0,1,'R');

$pdf->Cell(40,6,'Total Amount (All Bills):',0,0);
$pdf->Cell(30,6,number_format($sum_total_amount,2),0,1,'R');

$pdf->Cell(40,6,'Total Paid (All Payments):',0,0);
$pdf->Cell(30,6,number_format($sum_total_paid,2),0,1,'R');

$pdf->Cell(40,6,'Remaining Balance (Total):',0,0);
$pdf->Cell(30,6,number_format($sum_total_amount - $sum_total_paid,2),0,1,'R');

$pdf->Ln(6);

// ---------------------------
// Signature area
// ---------------------------
$pdf->Cell(0,4,str_repeat('_', 120),0,1,'L');
$pdf->Cell(0,5,'Prepared by: ' . (isset($_SESSION['auth_user']['username']) ? $_SESSION['auth_user']['username'] : 'Administrator'),0,1,'L');
// Add report generated date/time
$pdf->SetFont('Arial','I',9);
$generated_at = date('F d, Y H:i:s');
$pdf->Cell(0,5,"Generated on: $generated_at",0,1,'L');
$pdf->Ln(2);

$pdf->Ln(4);
$pdf->SetFont('Arial','I',8);
$pdf->Cell(0,4,'This is a system generated report.',0,1,'C');

// Output PDF to browser
$pdf->Output('I', 'bill_payment_report.pdf');
exit;
?>
