<?php
session_start();
require 'config/dbcon.php';
require('fpdf/fpdf.php');

$reservation_id = intval($_GET['id'] ?? 0);
if($reservation_id <= 0){
    die("Invalid reservation ID.");
}

// Fetch reservation based on ID
$res = mysqli_query($con, "
    SELECT r.*, u.name AS unit_name 
    FROM reservations r
    JOIN units u ON r.unit_id = u.id
    WHERE r.id = $reservation_id
    LIMIT 1
");

if(mysqli_num_rows($res) == 0){
    die("Reservation not found.");
}

$row = mysqli_fetch_assoc($res);

// Generate receipt number
$receipt_no = 'BOOKINGRCPT-' . str_pad($row['id'], 5, '0', STR_PAD_LEFT);

// Determine who generated the payment
$generated_by = ($row['payment_method'] === 'cash') ? 'Generated by Admin' : $row['fname'].' '.$row['lname'];

// Create PDF
$pdf = new FPDF();
$pdf->AddPage();

// --- HEADER ---
// Logo
$pdf->Image('images/logo.png',10,10,40); // x, y, width
$pdf->SetFont('Arial','B',20);
$pdf->SetTextColor(0,0,80);
$pdf->Cell(0,10,'E-RECEIPT',0,1,'R');
$pdf->SetFont('Arial','',12);
$pdf->SetTextColor(0,0,0);
$pdf->Cell(0,6,"Receipt No: $receipt_no",0,1,'R');
$pdf->Cell(0,6,"Date: ".date('F-m-Y'),0,1,'R');

$pdf->Ln(20); // space after header

// --- CUSTOMER INFO ---
$pdf->SetFont('Arial','B',14);
$pdf->SetFillColor(230,230,230); // light grey background
$pdf->Cell(0,8,'Guest Information',0,1,'L',true);

$pdf->SetFont('Arial','',12);
$pdf->Cell(0,6,'Name: '.$row['fname'].' '.$row['lname'],0,1);
$pdf->Cell(0,6,'Email: '.$row['email'],0,1);
$pdf->Cell(0,6,'Phone: '.$row['phone'],0,1);
$pdf->Cell(0,6,'Move-in Date: '.$row['move_in_date'],0,1);
$pdf->Cell(0,6,'Payment Generated By: '.$generated_by,0,1);

$pdf->Ln(10);

//PAYMENT DETAILS TABLE ---
$pdf->SetFont('Arial','B',12);
$pdf->SetFillColor(200,200,200); // header background
$pdf->SetTextColor(0,0,0);

// Column widths (proportional for A4 width)
$w_unit = 45;
$w_method = 35;
$w_amount = 40;
$w_status = 30;
$w_date = 40;

$pdf->Cell($w_unit,8,'Unit',1,0,'C',true);
$pdf->Cell($w_method,8,'Payment Method',1,0,'C',true);
$pdf->Cell($w_amount,8,'Downpayment',1,0,'C',true);
$pdf->Cell($w_status,8,'Status',1,0,'C',true);
$pdf->Cell($w_date,8,'Payment Date',1,1,'C',true);

$pdf->SetFont('Arial','',12);
$pdf->Cell($w_unit,8,$row['unit_name'],1,0,'C');
$pdf->Cell($w_method,8,$row['payment_method'],1,0,'C');
$pdf->Cell($w_amount,8,''.number_format($row['amount_paid'],2),1,0,'C');
$pdf->Cell($w_status,8,$row['payment_status'],1,0,'C');
$pdf->Cell($w_date,8,date('F-m-Y', strtotime($row['payment_date'])),1,1,'C');

$pdf->Ln(15);

// --- FOOTER ---
$pdf->SetFont('Arial','I',12);
$pdf->Cell(0,6,'Thank you for your payment!',0,1,'C');
$pdf->Cell(0,6,'This is a system generated receipt.',0,1,'C');

// Output PDF
$pdf->Output('I','Receipt_'.$receipt_no.'.pdf');
?>
