<?php
session_start();
require('config/dbcon.php');

if (!isset($_SESSION['auth'])) {
    $_SESSION['message'] = "Please login to access the dashboard.";
    header("Location: ../login.php");
    exit(0);
}

$allowed_roles = ['admin', 'employee'];
$user_role = $_SESSION['auth_role'] ?? '';
if (!in_array($user_role, $allowed_roles)) {
    $_SESSION['message'] = "You are not authorized to access this page.";
    header("Location: ../login.php");
    exit(0);
}

// PAGINATION SETTINGS
$limit = 20;
$page = isset($_GET['page']) ? (int)$_GET['page'] : 1;
if ($page < 1) $page = 1;
$offset = ($page - 1) * $limit;

// BASE QUERY
$baseQuery = "
    FROM bills b
    LEFT JOIN payments p ON b.id = p.bill_id
    LEFT JOIN renters r ON b.renter_id = r.id
    LEFT JOIN units u ON b.unit_id = u.id
    WHERE 1=1
";

// FILTERS
$filters = [];
$where = "";

//SEARCH ADDITION
$searchTerm = '';
if (!empty($_GET['search'])) {
    $searchTerm = mysqli_real_escape_string($con, trim($_GET['search']));
    $where .= " AND (
        CONCAT(r.first_name, ' ', r.last_name) LIKE '%$searchTerm%' OR
        r.first_name LIKE '%$searchTerm%' OR
        r.last_name LIKE '%$searchTerm%' OR
        u.name LIKE '%$searchTerm%' OR
        b.reference_id LIKE '%$searchTerm%' OR
        b.billing_month LIKE '%$searchTerm%' OR
        b.status LIKE '%$searchTerm%' OR
        p.payment_type LIKE '%$searchTerm%' OR
        b.generated_by LIKE '%$searchTerm%' OR
        b.generated_role LIKE '%$searchTerm%'
    )";
    $filters[] = "Search: <b>$searchTerm</b>";
}

if (isset($_GET['filter'])) {
    if (!empty($_GET['start_date']) && !empty($_GET['end_date'])) {
        $start = mysqli_real_escape_string($con, $_GET['start_date']);
        $end = mysqli_real_escape_string($con, $_GET['end_date']);
        $where .= " AND DATE(b.created_at) BETWEEN '$start' AND '$end'";
        $filters[] = "From <b>$start</b> to <b>$end</b>";
    }

    if (!empty($_GET['month'])) {
        $month = mysqli_real_escape_string($con, $_GET['month']);
        $where .= " AND MONTH(b.created_at) = '$month'";
        $filters[] = "Month: <b>" . date("F", mktime(0, 0, 0, $month, 1)) . "</b>";
    }

    if (!empty($_GET['year'])) {
        $year = mysqli_real_escape_string($con, $_GET['year']);
        $where .= " AND YEAR(b.created_at) = '$year'";
        $filters[] = "Year: <b>$year</b>";
    }

    if (!empty($_GET['creator_name'])) {
        $creator_name = mysqli_real_escape_string($con, $_GET['creator_name']);
        $where .= " AND (
            b.generated_by LIKE '%$creator_name%' 
            OR b.generated_role LIKE '%$creator_name%'
        )";
        $filters[] = "Generated by: <b>$creator_name</b>";
    }
}

// COUNT FOR PAGINATION
$count_sql = "SELECT COUNT(DISTINCT b.id) AS total " . $baseQuery . $where;
$count_result = mysqli_query($con, $count_sql);
$total_rows = mysqli_fetch_assoc($count_result)['total'] ?? 0;
$total_pages = ($total_rows > 0) ? ceil($total_rows / $limit) : 1;

// MAIN QUERY
$query = "
    SELECT 
        b.id AS bill_id,
        b.reference_id,
        b.billing_month,
        b.due_date,
        b.unit_price,
        b.addon_total,
        b.total_amount,
        b.late_fee,
        b.status AS bill_status,
        b.created_at,
        b.generated_by,
        b.generated_role,
        CONCAT(r.first_name, ' ', r.last_name) AS renter_name,
        u.name AS unit_name,
        IFNULL(SUM(p.amount), 0) AS total_paid,
        GROUP_CONCAT(DISTINCT p.payment_type SEPARATOR ', ') AS payment_types
    " . $baseQuery . $where . "
    GROUP BY b.id
    ORDER BY b.created_at DESC
    LIMIT $limit OFFSET $offset
";

$result = mysqli_query($con, $query) or die("Query failed: " . mysqli_error($con));

include('includes/header.php');
?>

<div class="container-fluid px-4">
    <h1 class="mt-4">Reports</h1>

    <!--SEARCH + FILTER FORM -->
    <div class="card mt-3 shadow">
        <div class="card-body">
            <form method="GET" class="row g-3 align-items-end">
                <div class="col-md-4">
                    <label>Search All</label>
                    <input type="text" id="searchInput" name="search" class="form-control" placeholder="Search renter, unit, or bill..." value="<?= htmlspecialchars($_GET['search'] ?? '') ?>">
                </div>

                <div class="col-md-2">
                    <label>Start Date</label>
                    <input type="date" name="start_date" class="form-control" value="<?= $_GET['start_date'] ?? '' ?>">
                </div>
                <div class="col-md-2">
                    <label>End Date</label>
                    <input type="date" name="end_date" class="form-control" value="<?= $_GET['end_date'] ?? '' ?>">
                </div>
                <div class="col-md-2">
                    <label>Month</label>
                    <select name="month" class="form-select">
                        <option value="">All</option>
                        <?php for ($m=1; $m<=12; $m++): ?>
                            <option value="<?= $m ?>" <?= (isset($_GET['month']) && $_GET['month']==$m)?'selected':'' ?>>
                                <?= date("F", mktime(0,0,0,$m,1)) ?>
                            </option>
                        <?php endfor; ?>
                    </select>
                </div>
                <div class="col-md-2">
                    <label>Year</label>
                    <select name="year" class="form-select">
                        <option value="">All</option>
                        <?php for ($y=date('Y'); $y>=2020; $y--): ?>
                            <option value="<?= $y ?>" <?= (isset($_GET['year']) && $_GET['year']==$y)?'selected':'' ?>><?= $y ?></option>
                        <?php endfor; ?>
                    </select>
                </div>

                <div class="col-md-12 text-end mt-2">
                    <button type="submit" name="filter" class="btn btn-primary"><i class="fa fa-filter"></i> Apply</button>
                    <a href="report_bill.php" class="btn btn-secondary"><i class="fa fa-rotate-left"></i> Reset</a>
                </div>
            </form>
        </div>
    </div>

    <!-- FILTER SUMMARY -->
    <?php if (!empty($filters)): ?>
        <div class="alert alert-info mt-3">
            <strong>Applied Filters:</strong> <?= implode(' | ', $filters) ?>
        </div>
    <?php endif; ?>

    <!-- TABLE -->
    <div class="card mt-3 shadow">
        <div class="card-body table-responsive">
            <div class="d-flex justify-content-between mb-3">
                <h5 class="fw-bold mt-2">Bills and Payments Overview</h5>
                <div>
                    <button class="btn btn-success btn-sm" id="exportCSV"><i class="fa-regular fa-file-excel"></i> Export Excel</button>
                    <button class="btn btn-danger btn-sm" id="exportPDF"><i class="fa fa-file-pdf"></i> Export PDF</button>
                    <button id="" class="btn btn-secondary btn-sm" onclick="printReport()"><i class="fa fa-print"></i> Print</button>
                </div>
            </div>
             <div id="reportTable" >
                <table class="table table-bordered table-striped align-middle">
                    <thead class="table-dark text-center">
                        <tr>
                            <th>#</th>
                            <th>Reference ID</th>
                            <th>Renter</th>
                            <th>Unit</th>
                            <th>Billing Month</th>
                            <th>Due Date</th>
                            <th>Total Amount</th>
                            <th>Amount Paid</th>
                            <th>Payment Type(s)</th>
                            <th>Status</th>
                            <th>Generated By</th>
                            <!-- <th>Role</th> -->
                            <th>Created At</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php 
                        if (mysqli_num_rows($result) > 0):
                            $i = $offset + 1;
                            while ($row = mysqli_fetch_assoc($result)):
                        ?>
                        <tr>
                            <td><?= $i++ ?></td>
                            <td><?= htmlspecialchars($row['reference_id']) ?></td>
                            <td><?= htmlspecialchars($row['renter_name'] ?? '—') ?></td>
                            <td><?= htmlspecialchars($row['unit_name'] ?? '—') ?></td>
                            <td><?= date('F', strtotime($row['due_date'])) ?></td> 
                            <td><?= htmlspecialchars($row['due_date']) ?></td>
                            <td class="text-end"><?= number_format($row['total_amount'], 2) ?></td>
                            <td class="text-end"><?= number_format($row['total_paid'], 2) ?></td>
                            <td><?= htmlspecialchars($row['payment_types'] ?? '—') ?></td>
                            <td>
                                <?php
                                    $badge = match($row['bill_status']) {
                                        'paid' => 'success',
                                        'partial' => 'warning',
                                        'open' => 'secondary',
                                        default => 'dark'
                                    };
                                ?>
                                <span class="badge bg-<?= $badge ?>"><?= ucfirst($row['bill_status']) ?></span>
                            </td>
                            <td><?= htmlspecialchars(ucfirst($row['generated_role'] ?? '—')) ?></td>
                            <td><?= date("Y-m-d H:i", strtotime($row['created_at'])) ?></td>
                        </tr>
                        <?php endwhile; else: ?>
                            <tr><td colspan="13" class="text-center text-muted">No records found.</td></tr>
                        <?php endif; ?>
                    </tbody>
                </table>
           </div>

            <!-- PAGINATION -->
            <?php
                $query_params = $_GET;
                unset($query_params['page']);
                $query_str = http_build_query($query_params);
                $base_url = basename($_SERVER['PHP_SELF']);
                $base_url .= $query_str ? "?$query_str&" : "?";
                $prev_page = ($page > 1) ? $page - 1 : 1;
                $next_page = ($page < $total_pages) ? $page + 1 : $total_pages;
            ?>

            <nav aria-label="Page navigation" class="mt-3">
                <ul class="pagination justify-content-end">
                    <li class="page-item <?= ($page <= 1) ? 'disabled' : '' ?>">
                        <a class="page-link" href="<?= ($page > 1) ? "{$base_url}page={$prev_page}" : '#' ?>">Prev</a>
                    </li>

                    <?php for ($i = 1; $i <= $total_pages; $i++): ?>
                        <li class="page-item <?= ($i == $page) ? 'active' : '' ?>">
                            <a class="page-link" href="<?= $base_url ?>page=<?= $i ?>"><?= $i ?></a>
                        </li>
                    <?php endfor; ?>

                    <li class="page-item <?= ($page >= $total_pages) ? 'disabled' : '' ?>">
                        <a class="page-link" href="<?= ($page < $total_pages) ? "{$base_url}page={$next_page}" : '#' ?>">Next</a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</div>

<?php include('includes/footer.php'); ?>

<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/jszip/dist/jszip.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/pdfmake/build/pdfmake.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/pdfmake/build/vfs_fonts.js"></script>
<script src="https://cdn.jsdelivr.net/npm/datatables.net-buttons/js/buttons.html5.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/datatables.net-buttons/js/buttons.print.min.js"></script>

<script>

    document.getElementById('exportCSV').addEventListener('click', function () {
        let queryString = window.location.search.substring(1);
        window.open('export_bill_payment_xlsx.php?' + queryString, '_blank');
    });

    document.getElementById('exportPDF').addEventListener('click', function () {
        // Get current full URL query string
        let queryString = window.location.search.substring(1);

        // Open the PDF generator with all filters applied
        window.open('bill_payment_report_pdf.php?' + queryString, '_blank');
    });

// document.getElementById('exportCSV').addEventListener('click', function () {
//     let table = document.querySelector('table');
//     let rows = table.querySelectorAll('tr');
//     let csv = [];

//     rows.forEach(function (row) {
//         let cols = row.querySelectorAll('th, td');
//         let rowData = [];
//         cols.forEach(function (col) {
//             let text = col.innerText.trim();

//             //  Prevent Excel from reformatting dates or long numbers
//             if (/^\d{4}-\d{2}-\d{2}/.test(text)) { 
//                 text = "'" + text; // add apostrophe to force text format
//             }

//             //  Clean commas and quotes
//             text = text.replace(/(\r\n|\n|\r)/gm, '').replace(/"/g, '""');

//             rowData.push('"' + text + '"');
//         });
//         csv.push(rowData.join(','));
//     });

//     let csvFile = new Blob([csv.join('\n')], { type: 'text/csv;charset=utf-8;' });
//     let downloadLink = document.createElement('a');
//     downloadLink.download = 'bill_reports.csv';
//     downloadLink.href = URL.createObjectURL(csvFile);
//     downloadLink.style.display = 'none';
//     document.body.appendChild(downloadLink);
//     downloadLink.click();
//     document.body.removeChild(downloadLink);
// });

// document.getElementById('exportPDF').addEventListener('click', function () {
//     let printWindow = window.open('', '', 'height=900,width=1200');
//     printWindow.document.write('<html><head><title>Bill Reports PDF</title>');
//     printWindow.document.write('<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">');
//     printWindow.document.write('</head><body>');
//     printWindow.document.write('<h3 class="text-center mb-4">Bill Reports</h3>');
//     printWindow.document.write(document.querySelector('reportTable').innerHTML);
//     printWindow.document.write('</body></html>');
//     printWindow.document.close();
//     printWindow.print();
// });

// $(document).ready(function() {
//     $('#billTable').DataTable({
//         dom: 'Bfrtip',
//         paging: false, // pagination
//         ordering: false,
//         buttons: [
//             { extend: 'csv', text: '<i class="fa fa-file-csv"></i> CSV', className: 'btn btn-outline-success btn-sm' },
//             { extend: 'pdf', text: '<i class="fa fa-file-pdf"></i> PDF', className: 'btn btn-outline-danger btn-sm' }
//         ]
//     });
// });



// document.getElementById('exportPDF').addEventListener('click', function () {
//     // Get the current search/filter text
//     let searchQuery = document.getElementById('searchInput')?.value || '';

//     // Open the export PHP script with the search keyword
//     window.open('report_pdf.php?search=' + encodeURIComponent(searchQuery), '_blank');
// });


function printReport() {
    // Open a new window
    var printWindow = window.open('', '_blank', 'height=900,width=1200');

    // Business info
    var logo = 'images/logo.png'; // Make sure the path is correct
    var businessName = 'Monings Rental Services';
    var address = '1438-B M.J.Cuenco Ave, Brgy Mabolo, Cebu City';
    var phone = '09123456789';
    var email = 'cuy@gmail.com';

    // Get the table element itself, not just innerHTML
    var table = document.querySelector("#reportTable table");
    if (!table) {
        alert("No table found to print!");
        return;
    }

    // Build print HTML
    var html = `
        <html>
        <head>
            <title>Bill Report</title>
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
            <style>
                body { font-family: Arial, sans-serif; margin: 20px; }
                .header { text-align: center; margin-bottom: 20px; }
                .header img { height: 60px; margin-bottom: 10px; }
                .header h2 { margin: 0; font-size: 22px; }
                .header p { margin: 0; font-size: 14px; }
                table { width: 100%; border-collapse: collapse; font-size: 12px; }
                th, td { border: 1px solid #000; padding: 4px; text-align: center; }
                th { background-color: #333; color: #fff; }
                .table-responsive { overflow-x: auto; }
            </style>
        </head>
        <body>
            <div class="header">
                <img src="${logo}" alt="Logo">
                <h2>${businessName}</h2>
                <p>${address}</p>
                <p>Phone: ${phone} | Email: ${email}</p>
                <p>Generated: ${new Date().toLocaleString()}</p>
            </div>
            <div class="table-responsive">
                ${table.outerHTML}
            </div>
        </body>
        </html>
    `;

    // Write to new window and print
    printWindow.document.write(html);
    printWindow.document.close();
    printWindow.focus();
    printWindow.print();
}






    
</script>

